
DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (
  id INT PRIMARY KEY,
  phone VARCHAR(50) NOT NULL,
  experiences INT NOT NULL
);

DROP TABLE IF EXISTS students;
CREATE TABLE students (
  id INT NOT NULL PRIMARY KEY,
  year VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL
);
